name: Generate contributors

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      id: contributors
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        avatarSize: 42

    - name: Modify README.md
      uses: jaywcjlove/github-action-modify-file-content@main
      with:
        path: README.md
        openDelimiter: '<!--GAMFC-->'
        closeDelimiter: '<!--GAMFC-END-->'
        body: '${{steps.contributors.outputs.htmlList}}'
